# Generated by Django 2.2.13 on 2020-06-11 14:04

from django.db import migrations, models
import djongo.models.fields
import prueba.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('usuario', djongo.models.fields.EmbeddedField(model_container=prueba.models.Usuario, null=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
