# Generated by Django 2.2.13 on 2020-06-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('almacenamiento_disp', models.IntegerField()),
                ('id_H_Descargas', models.IntegerField()),
                ('id_Publicacion', models.IntegerField()),
                ('id_PDR', models.IntegerField()),
            ],
        ),
    ]
