# Generated by Django 2.2.13 on 2020-06-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='usuario',
        ),
    ]
