# Generated by Django 2.2.13 on 2020-06-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_auto_20200611_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
