# Generated by Django 2.2.13 on 2020-06-11 15:54

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0005_delete_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
